apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
        - name: app
          image: jeancarlosns/conversao-temperatura:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
