name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3.1.0

      - name: Logar no Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Construção da imagem Docker
        uses: docker/build-push-action@v3.1.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: teste-tempotelecom:v1

